export const routePaths = {
  root: `/`,
  login: `/login`,
  activateUser: `/activate-user`,
  changeEmail: `/change-email`,
  dashboard: `/dashboard`,
  forgotPassword: `/forgot-password`,
  resetPassword: `/reset-password`,
  findSalaries: `/find-salaries`,
  companyReviews: `/company-reviews`,
  resumeReady: `/resume-ready`,
  applyForJob: `/apply-for-job`,
  aboutUs: `/about-us`,
  contactUs: `/contact-us`,
  publicResumeinfo: `/public-resume-info`,
  helps: `/helps`,
  legalTerms: `/legal-terms`,
  privacyPolicy: `/terms-and-conditions/privacy-policy`,
  termsAndService: `/terms-and-conditions/terms-and-services`,
  communityGuideline: `/terms-and-conditions/community-guideline`,
  cookieStatement: `/terms-and-conditions/cookie-statement`,
  accountSettings: `/account-settings`,
  Message: `/message`,
  Resume: `/resume`,
  Search: `/searchterm`,

  employer: {
    signup: `/signup/employer`,
    dashboard: `/employer/dashboard`,
    postJob: `/employer/job/create`,
    editJob: `/employer/job/edit`,
    searchResume: `/employer/search-resumes`,
    employerAccount: `/employer-account`,
    payment: `/payment`,
    billingHistory: `/billing-history`,
    pricing: `/pricing`,
  },

  employees: {
    companyReview: `/employee/company-reviews`,
    findSalary: `/employee/find-salaries`,
    myJobs: `/employee/my-jobs`,
    profile: `/employee/profile`,
    createResume: `/employee/resume`,
    showResume: "/employee/view-profile",
  },

  contractor: {
    dashboard: `/`,
    signup: `/signup/contractor`,
    applicationSubmit: `/contractor/application-submitted`,
  },
};
