export const endpoints = {
  public: {
    login: `/loginuser`,
    signup: `/createuser`,
    signupSSO: `/createusersso`,
    activateUser: `/activateuser`,
    changeEmail: `/updateEmailconfirmation`,
    checkSignInOTP: `/otpcheck`,
    forgotPassword: `/forgotpassword`,
    resetPassword: `/forgotpassconfirmation`,
    getallJobs: `/getalljobs`,
    getallfeedJobs:`/getallfeedjobs`,
    getpublicJobs: `/getpublicjobs`,
    searchallJobs: `/searchalljobs`,
    searchallfeedJobs:`searchallfeedjobs`,
    gblsearchJobs: `/gblsearchjobs`,
    generateMonthlyBilling : `/generatemonthlybilling `,
    recentsearchespublic : `/recentsearchespublic`
  },
  private: {
    logout: `/logout`,
    getUserProfile: `/profile`,
    updateUserProfile: `/profile`,
    saveProfileEmailSignature: `/profile/email-signature`,
    getUser: `/getuser`,
    createemployer: `/createemployer`,
    searchJobs: `/searchjobstemplate`,
    getJobDetailsById: `/getjob`,
    copyJob: `/copyJob`,
    updateJob: `/updatejob`,
    createJob: `/addjob`,
    deleteJob: `/deletejob`,
    updateJobstatus: `/updatejobstatus`,
    getJob: `/getjob`,
    getalljobCategory: `/getalljobcategory`,    
    getalljobtype: `/getalljobtype`,
    getalljobschedule: `/getalljobschedule`,
    getallsupplementalpay: `/getallsupplementalpay`, 
    getallbenefitsoffered: `/getallbenefitsoffered`,    
    recentsearchJobs: `/recentsearchjobs`,
    recentsearches:`/recentsearches`,
    deleterecentsearchJobs:`\deleterecentsearchjobs`,
    updateAccounttype: `/updateAccounttype`,
    updatePhone: `/updatePhone`,
    updateEmail: `/updateEmail`,
    updatePassword: `/updatePassword`,
    updateAccountname: `/updateAccountname`,
    createResume: `/createresume`,
    updateResume: `/updateresume`,
    getResume: `/getresume`,
    getResumebyUser: `/getresumesbyuser`,
    createEducation: `/createeducation`,
    updateEducation: `/updateeducation`,
    deleteEducation: `/deleteeducation`,
    getEducation: `/geteducation`,
    getallEducation: `/getalleducation`,
    createWorkExperience: `/createworkexperience`,
    updateWorkExperience: `/updateworkexperience`,
    deleteWorkExperience: `/deleteworkexperience`,
    getWorkExperience: `/getworkexperience`,
    getallWorkExperience: `/getallworkexperience`,
    createCurricularActivities: `/createcurricularactivities`,
    updateCurricularActivities: `/updatecurricularactivities`,
    deleteCurricularActivities: `/deletecurricularactivities`,
    getallCurricularActivities: `/getallcurricularactivities`,
    isResumePrivate: `/isresumeprivate`,
    resumeHeadline: `/resumeheadline`,
    createDesiredJob: `/createdesiredjob`,
    updateDesiredJob: `/updatedesiredjob`,
    getDesiredJob: `/getdesiredjob`,
    getdesiredJobbyuid: `/getdesiredjobbyuid`,
    jobSavebyUser: `/jobsavebyuser`,
    getJobSaved: `/getjobsaved`,
    deleteJobSaved: `/deletejobsaved`,
    jobApply: `/jobapply`,
    getJobAppliedbyUser: `/getjobappliedbyuser`,
    getallpredealCategory: `/getallpredealcategory`,
    addpredealQuestions:`/addpredealquestions`,
    getpredealQuestions:`/getpredealquestions`,
    getallpredealQuestions:`/getallpredealquestions`,
    savepredealQuestions:`/savepredealquestions`,
    searchResumes:`/searchresumes`,
    getallResumes:`/getallresumes`,
    getAllJobSaved: `/getalljobsaved`,
    getAllJobApplied: `/getalljobappliedbyuser`,
    getAllInterview: `/getalljobappliedtointerview`,
    getAllJobArchived: `/getalljobappliedtoarchived`,
    updateJobAppliedStatus: `/updatejobappliedstatus`,
    getEmpUsersbyCon: `/getempusersbycon`,
    getConUsersbyEmp: `/getconusersbyemp`,
    getAllConversation: `/getallconversation`,
    createConversation: `/createconversation`,
    getallJobtitle: `/getalljobtitle`,
    getallJobcompany: `/getalljobcompany`,
    getalldesiredJobtitle:`/getalldesiredjobtitle`,
    getallCompany: `/getallcompany`,
    getallworkExperiencecount: `/getallworkexperiencecount`,
    getallMilitary: `/getallmilitary`,
    getcountEducation: `/getcounteducation`,
    getallAssessment: `/getallassessment`,
    invitejobtoApply: `/invitejobtoapply`,
    getalljobInvited:`/getalljobinvited`,
    getalljobRejected:`/getallrejected`,
    getallunderReview:`/getallunderreview`,
    deletejobInvited:`/deletejobinvited`, 
    getBillingHistory: `/getbillinghistory`,
    getCurMonBilling: `/getcurmonbilling`,
    getTodayBilling: `/gettodaybilling`,
    monthlyBillingPayment: `/monthlybillingpayment`,
    retrieveCardDetails: `/retrievecarddetails`,
    getallJobsCountbyUser: `/getalljobscountbyuser`,
    getallInvitedJobsCount: `/getallinvitedjobscount`,
    updateStripeCard: `/updatestripecard`,
  },
};
